name: Backend

on:
  workflow_run:
    workflows: [ "frontend" ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
      - uses: ramsey/composer-install@v2

      - name: Install packages
        run: composer install

      - name: Initialize project
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Execute tests
        run: php artisan test

      - name: Report
        run: curl https://${{ secrets.SERVER_HOST }}/api/_internal/a38a44bb8e660ed4d2a990c9046135e7
