name: CD
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: path_changed
        with:
          filters: |
            frontend:
              - 'resources/**'
              - 'vite.config.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

      - uses: pnpm/action-setup@v2
        if: steps.path_changed.outputs.frontend == 'true'
        with:
          version: latest

      - uses: actions/setup-node@v3
        if: steps.path_changed.outputs.frontend == 'true'
        with:
          cache: 'pnpm'

      - uses: yizhoumo/setup-ossutil@v1
        if: steps.path_changed.outputs.frontend == 'true'
        with:
          endpoint: ${{ secrets.OSS_GDCN_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_GDCN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_GDCN_ACCESS_KEY_SECRET }}

      - name: Install packages
        if: steps.path_changed.outputs.frontend == 'true'
        run: pnpm install

      - name: Copy .env
        if: steps.path_changed.outputs.frontend == 'true'
        run: cp .env.example .env

      - name: Add ASSET_URL
        if: steps.path_changed.outputs.frontend == 'true'
        run: echo 'ASSET_URL=${{ secrets.ASSET_URL }}' >> .env

      - name: Build
        if: steps.path_changed.outputs.frontend == 'true'
        run: pnpm run build

      - name: Deploy to oss
        if: steps.path_changed.outputs.frontend == 'true'
        run: |
          ossutil rm -rf ${{ secrets.OSS_PATH }}
          ossutil cp -rf public/build ${{ secrets.OSS_PATH }}
  backend:
    runs-on: ubuntu-latest
    needs:
      - frontend
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
      - uses: ramsey/composer-install@v2

      - name: Install packages
        run: composer install

      - name: Initialize project
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Execute tests
        run: php artisan test

      - name: Update
        run: curl --request POST ${{ secrets.UPDATER_URL }}
