name: CD
on: push

jobs:
    deploy:
        name: Build and deploy

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node: [ latest ]

        runs-on: ${{ matrix.os }}

        steps:
            -   name: Checkout
                uses: actions/checkout@master

            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "latest"

            -   uses: "ramsey/composer-install@v2"

            -   name: Install backend dependencies
                run: composer install

            -   name: Setup PNPM
                uses: pnpm/action-setup@v2.2.2
                with:
                    version: latest

            -   name: Setup Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'pnpm'

            -   name: Install dependencies
                run: pnpm install

            -   name: Build
                run: pnpm run build

            -   name: Install oss utils
                uses: yizhoumo/setup-ossutil@v1
                with:
                    endpoint: ${{ secrets.OSS_GDCN_ENDPOINT }}
                    access-key-id: ${{ secrets.OSS_GDCN_ACCESS_KEY_ID }}
                    access-key-secret: ${{ secrets.OSS_GDCN_ACCESS_KEY_SECRET }}

            -   name: Deploy to oss
                run: |
                    ossutil rm -rf oss://gdcn/static/website
                    ossutil cp -rf ./public/build oss://gdcn/static/website
