on: push
name: CI

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: laradock/workspace:master-8.1
    services:
      database:
        image: mariadb
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: gdcn
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Install composer dependencies
        run: |
          composer install
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Run test
        run: vendor/bin/phpunit tests/
      - name: Post deploy request
        run: curl -X POST -F 'secret=${{ secrets.APP_HOOK_SECRET }}' ${{ secrets.APP_HOOK_URL }}
