on: push
name: CI

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      mysql:
        image: mariadb
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: gdcn
        ports:
          - 33306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Install composer dependencies
        run: |
          composer install
      - name: Install front-end dependencies
        run: |
          npm install --global pnpm
          pnpm install
      - name: Build front-end resources
        run: |
          pnpm run build
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
