name: CI
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: laradock/workspace:master-8.1
        services:
            database:
                image: mariadb
                env:
                    MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
                    MARIADB_DATABASE: gdcn
                ports:
                    - 3306:3306
        steps:
            -   uses: actions/checkout@v3

            -   name: Install packages
                run: |
                    rm -f composer.lock
                    composer update --no-interaction --no-ansi

            -   name: Initialize project
                run: |
                    cp .env.ci .env
                    php artisan key:generate

            -   name: Execute tests
                run: php artisan test
