name: Frontend
on: push

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: shivammathur/setup-php@v2
      - uses: ramsey/composer-install@v2
      - uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: ${{ secrets.OSS_GDCN_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_GDCN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_GDCN_ACCESS_KEY_SECRET }}

      - name: Install packages
        run: |
          pnpm install
          composer install

      - name: Build
        run: pnpm run build

      - name: Deploy to oss
        run: |
          ossutil rm -rf ${{ secrets.OSS_PATH }}
          ossutil cp -rf dist ${{ secrets.OSS_PATH }}
