on: push
name: '静态代码检查'

jobs:
  stan:
    runs-on: ubuntu-latest
    container:
      image: laradock/workspace:master-8.1
    steps:
      - uses: actions/checkout@v3

      - name: '更新依赖'
        run: |
          rm composer.lock
          composer update --no-interaction --no-ansi

      - name: '初始化项目'
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: '跑检查'
        run: vendor/bin/phpstan analyse
