on: push
name: '测试'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: laradock/workspace:master-8.1
    services:
      database:
        image: mariadb
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: gdcn
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3

      - name: '[后端] 更新依赖'
        run: |
          rm composer.lock
          composer update --no-interaction --no-ansi

      - name: '初始化项目'
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: '跑测试'
        run: php artisan test

      - name: '发送部署请求'
        run: curl -X POST -F 'secret=${{ secrets.APP_HOOK_SECRET }}' ${{ secrets.APP_HOOK_URL }}
